# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

variables:
  environment: development

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build the image
  inputs:
    containerRegistry: 'docker-registry-devops'
    repository: 'devops-angular-envconfig'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    arguments: --build-arg Environment=sit
- task: Docker@2
  displayName: Push the image
  inputs:
    containerRegistry: 'docker-registry-devops'
    repository: 'devops-angular-envconfig'
    command: 'push'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- pwsh: |       
      Get-ChildItem -Path $(Build.SourcesDirectory)\*.* -Recurse -Force | Out-String -Width 180
  errorActionPreference: continue
  displayName: 'List content'
  continueOnError: true

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'devops-aks-cluster'
    namespace: 'dev'
    manifests: | 
      $(Build.SourcesDirectory)/Manifests/app.yml
      $(Build.SourcesDirectory)/Manifests/service.yml